Repository HS-Continuity/Dashboard, pull requests merged in 2024-08, with the labels that each got.

#43 KAN-669 feat: 식품 조회 페이지에 재고 등록 api 연동 추가
  src/pages/customer/ProductEco.jsx
  src/pages/customer/ProductGeneral.jsx
Labels: API

#44 Kan-195 feat: 배송관리 배송상태 카운트 api 연동
  src/apis/apisDelivery.js
  src/pages/customer/Delivery.jsx
Labels: API

#46 Kan-513 style: 메인디자인설정
  src/assets/images/logo.png
  src/components/Buttons/ApplyButton.jsx
  src/components/Buttons/PromotionApplyButton.jsx
  src/components/Buttons/RegisterButton.jsx
  src/components/Cards/StatusCard.jsx
  src/components/Layouts/Main.jsx
  src/components/Layouts/MainHeader.jsx
  src/components/Layouts/Sidenav.jsx
  src/components/Layouts/Sidenav.module.css
  src/pages/customer/Delivery.jsx
  src/pages/customer/Inventory.jsx
  src/pages/customer/MemberManage.jsx
  src/pages/customer/Order.module.css
  src/pages/customer/OrderGeneral.jsx
  src/pages/customer/ProductEco.jsx
  src/pages/customer/ProductGeneral.jsx
  src/pages/customer/ProductTimesale.jsx
  src/pages/customer/Promotion.jsx
  src/pages/customer/Shipment.jsx
  src/pages/customer/Table.module.css
  src/stores/useAuthStore.js
Labels: HTML+CSS, Refactor

#47 KAN-693 feat: 쉽게 보기 페이지
  src/App.css
  src/App.jsx
  src/components/Easyview/LargeCursor.jsx
  src/components/Easyview/layout/EasyViewContent.jsx
  src/components/Easyview/layout/EasyViewContent.module.css
  src/components/Easyview/layout/EasyViewHeader.jsx
  src/components/Easyview/layout/EasyViewHeader.module.css
  src/components/Easyview/layout/EasyViewLayout.jsx
  src/components/Easyview/layout/MenuItems.jsx
  src/components/Easyview/layout/VoiceWaveButton.jsx
  src/components/Easyview/member/AddressList.jsx
  src/components/Easyview/member/CardList.jsx
  src/components/Easyview/product/ProductApplyModal.jsx
  src/components/Easyview/product/TimeSaleApplyModal.jsx
  src/components/Layouts/Main.jsx
  src/components/Layouts/MainHeader.jsx
  src/components/Layouts/Sidenav.jsx
  src/index.css
  src/main.jsx
  src/pages/customer/MemberManage.jsx
  src/pages/easyview/EasyMemberManage.jsx
  src/pages/easyview/EasyProductGeneral.jsx
  src/stores/fontSizeStore.js
  src/stores/largeCursorStore.js
  src/stores/speechStore.js
Labels: Feature, HTML+CSS, Setting

#51 Kan-113 style: 식품관리 식품 등록 UI 수정
  src/pages/customer/MemberManage.jsx
  src/pages/customer/ProductCreate.jsx
  src/pages/customer/ProductEco.jsx
  src/pages/customer/ProductEcoDetail.jsx
  src/pages/customer/ProductGeneral.jsx
  src/pages/customer/ProductGeneralDetail.jsx
  src/stores/useAuthStore.js
Labels: HTML+CSS

#52 KAN-194 style: 출고 상세 페이지 UI 수정
  src/pages/customer/ShipmentDetail.jsx
Labels: HTML+CSS

#53 Kan-114 style: 주문관리 상세 페이지 UI 수정
  src/components/Buttons/StatusChangeButton.jsx
  src/pages/customer/OrderGeneral.jsx
  src/pages/customer/OrderGeneralDetail.jsx
  src/pages/customer/OrderSubscription.jsx
Labels: HTML+CSS

#55 Kan-683 refactor: 로그인토큰관리 공통 로그인 기능 추가
  src/App.jsx
  src/pages/customer/Delivery.jsx
  src/pages/customer/ImageUploadTest.jsx
  src/pages/customer/Inventory.jsx
  src/pages/customer/MemberManage.jsx
  src/pages/customer/OrderGeneral.jsx
  src/pages/customer/OrderSubscription.jsx
  src/pages/customer/Promotion.jsx
  src/pages/customer/Shipment.jsx
Labels: Refactor

#57 KAN-176 style: 회원 상세 페이지 기본정보 UI 수정
  src/pages/customer/MemberManageDetail.jsx
Labels: HTML+CSS

#58 Kan-113 feat: 식품관리 타임세일식품 취소 api 연동
  src/apis/apisProducts.js
  src/apis/apisPromotion.js
  src/pages/customer/ProductCreate.jsx
  src/pages/customer/ProductGeneralDetail.jsx
  src/pages/customer/ProductTimeSaleDetail.jsx
Labels: API, HTML+CSS

#60 Kan-113 refactor: 식품관리 식품 삭제 api 연동 수정
  src/pages/customer/ProductEcoDetail.jsx
  src/pages/customer/ProductGeneralDetail.jsx
Labels: API, Refactor

#64 Kan-191 feat: 출고관리 출고조회 및 상세 데이터 수정
  src/pages/customer/Shipment.jsx
  src/pages/customer/ShipmentDetail.jsx
Labels: Refactor

#70 KAN-537 refactor: 회원관리 회원상세 메세지 수정
  src/App.jsx
  src/apis/apisMembers.js
  src/pages/customer/MemberManage.jsx
  src/pages/customer/MemberManageDetail.jsx
Labels: Refactor

#71 KAN-727 refactor: 식품 페이지 오류 수정
  src/apis/apisProducts.js
  src/pages/customer/MemberManage.jsx
  src/pages/customer/OrderGeneral.jsx
  src/pages/customer/ProductCreate.jsx
  src/pages/customer/ProductEco.jsx
  src/pages/customer/ProductEcoDetail.jsx
  src/pages/customer/ProductGeneral.jsx
  src/pages/customer/ProductGeneralDetail.jsx
  src/pages/customer/ProductTimesale.jsx
Labels: BugFix, Refactor

#75 KAN-735 refactor: 페이지별 기능 수정
  src/App.jsx
  src/apis/apisOrders.js
  src/assets/audio/newVoice.m4a
  src/assets/audio/newVoice2.m4a
  src/assets/audio/taehoVoice.m4a
  src/pages/customer/Delivery.jsx
  src/pages/customer/Inventory.jsx
  src/pages/customer/MemberManage.jsx
  src/pages/customer/NotFound.jsx
  src/pages/customer/OrderGeneral.jsx
  src/pages/customer/OrderSubscription.jsx
  src/pages/customer/Promotion.jsx
  src/pages/customer/Shipment.jsx
  src/pages/customer/ShipmentDetail.jsx
  src/stores/useAuthStore.js
Labels: Refactor

#73 KAN-377 feat: 회원 관리 페이지 레이아웃 재배치
  src/App.jsx
  src/components/Easyview/layout/EasyViewContent.jsx
  src/components/Easyview/layout/EasyViewHeader.jsx
  src/components/Easyview/layout/EasyViewHeader.module.css
  src/components/Easyview/layout/EasyViewLayout.jsx
  src/components/Easyview/layout/MenuItems.jsx
  src/pages/easyview/member/EasyMemberManage.jsx
Labels: HTML+CSS, Refactor

#74 KAN-380 feat: 식품 관리 페이지 레이아웃 재배치
  src/pages/easyview/EasyProductGeneral.jsx
  src/pages/easyview/product/EasyProductEco.jsx
  src/pages/easyview/product/EasyProductEcoDetail.jsx
  src/pages/easyview/product/EasyProductGeneral.jsx
  src/pages/easyview/product/EasyProductGeneralDetail.jsx
  src/pages/easyview/product/EasyProductTimeSale.jsx
  src/pages/easyview/product/EasyProductTimeSaleDetail.jsx
  src/pages/easyview/promotion/EasyPromotion.jsx
  src/pages/easyview/statistics/EasyStatistics.jsx
  src/stores/fontSizeStore.js
Labels: Feature, HTML+CSS

#82 Kan-118 feat/통계관리 통계 데이터 시각화
  package-lock.json
  package.json
  src/apis/apisStatistics.js
  src/components/Chart/BarChart.jsx
  src/components/Chart/LineChart.js
  src/components/Chart/LineChart.jsx
  src/pages/Home.jsx
Labels: Feature, API

#80 KAN-743 fix: 버그 수정
  package-lock.json
  package.json
  src/App.jsx
  src/components/Easyview/layout/MenuItems.jsx
  src/components/Layouts/Sidenav.jsx
  src/components/Layouts/Sidenav.module.css
  src/pages/customer/Delivery.jsx
  src/pages/customer/Inventory.jsx
  src/pages/customer/MemberAddress.jsx
  src/pages/customer/MemberManage.jsx
  src/pages/customer/MemberManageDetail.jsx
  src/pages/customer/OrderGeneral.jsx
  src/pages/customer/ProductCreate.jsx
  src/pages/customer/ProductEco.jsx
  src/pages/customer/ProductGeneral.jsx
  src/pages/customer/ProductTimesale.jsx
  src/pages/customer/Promotion.jsx
  src/pages/customer/Shipment.jsx
  src/pages/customer/ShipmentDetail.jsx
Labels: BugFix, Setting

#81 KAN-744 fix: 쉽게 보기 버그 수정
  src/pages/easyview/delivery/EasyDelivery.jsx
  src/pages/easyview/inventory/EasyInventory.jsx
  src/pages/easyview/member/EasyMemberManage.jsx
  src/pages/easyview/order/EasyOrderGeneral.jsx
  src/pages/easyview/order/EasyOrderGeneralDetail.jsx
  src/pages/easyview/order/EasyOrderSubscription.jsx
  src/pages/easyview/order/EasyOrderSubscriptionDetail.jsx
  src/pages/easyview/product/EasyProductEco.jsx
  src/pages/easyview/product/EasyProductEcoDetail.jsx
  src/pages/easyview/product/EasyProductGeneral.jsx
  src/pages/easyview/product/EasyProductGeneralDetail.jsx
  src/pages/easyview/product/EasyProductTimeSale.jsx
  src/pages/easyview/product/EasyProductTimeSaleDetail.jsx
  src/pages/easyview/promotion/EasyPromotion.jsx
  src/pages/easyview/shipment/EasyShipment.jsx
  src/pages/easyview/shipment/EasyShipmentDetail.jsx
  src/pages/easyview/statistics/EasyStatistics.jsx
Labels: BugFix, Feature

#83 KAN-116 feat: 메인 페이지 기능 완성
  src/apis/apisMain.js
  src/components/Layouts/MainHeader.jsx
  src/pages/Home.jsx
  src/pages/customer/Shipment.jsx
Labels: Feature, API

#85 KAN-691 refactor: 수정 사항
  src/components/Layouts/MainHeader.jsx
  src/pages/Home.jsx
  src/pages/customer/OrderGeneral.jsx
  src/pages/customer/Shipment.jsx
Labels: BugFix, Refactor

#88 대시보드 연이음 페이지 (v1.4)
  index.html
  src/assets/images/favicon.png
Labels: Deploy
